# Generated by Django 5.2 on 2025-04-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0002_alter_card_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['serial_no']},
        ),
        migrations.AddField(
            model_name='card',
            name='post_type',
            field=models.CharField(choices=[('ADVERTISEMENT', 'Advertisement'), ('CIRCULAR', 'Circular'), ('RESULT', 'Result'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='serial_no',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
