# Generated by Django 5.2 on 2025-04-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0003_alter_card_options_card_post_type_card_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='serial_no',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='card_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task_report_app.card')),
            ],
        ),
    ]
