# Generated by Django 5.2 on 2025-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0004_alter_card_serial_no_cardattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file_type',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='CardAttachment',
        ),
    ]
