# Generated by Django 5.2 on 2025-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0007_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
