# Generated by Django 5.2 on 2025-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0009_uploadedfile_remove_task_file_filecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='FileCollection',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
