# Generated by Django 5.2 on 2025-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0011_remove_task_file_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
