# Generated by Django 5.2 on 2025-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_report_app', '0012_task_is_archived_task_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post_type',
            field=models.CharField(choices=[('Advertisement', 'Advertisement'), ('Circular', 'Circular'), ('Result', 'Result'), ('Tender', 'Tender'), ('Other', 'Other')], default='Advertisement', max_length=50),
        ),
    ]
